### ISSUE TITLE
Got panic while parse pkg if it's AndroidManifest.xml has some problem.

### ISSUE THREAD

**Issue by Laitr0n** [shogo82148/androidbinary#73]
[ldfroezja.apk](https://drive.google.com/file/d/1lqZCQnV1I46UBa3EzbBK4F8AzVnEN4U2/view?usp=share_link)

```
panic: runtime error: index out of range [4294967167] with length 565

goroutine 22 [running]:
github.com/shogo82148/androidbinary.(*ResStringPool).GetString(...)
	/go/pkg/mod/github.com/shogo82148/androidbinary@v1.0.3/common.go:119
github.com/shogo82148/androidbinary.(*XMLFile).GetString(...)
	/go/pkg/mod/github.com/shogo82148/androidbinary@v1.0.3/xml.go:168
github.com/shogo82148/androidbinary.(*XMLFile).addNamespacePrefix(0x881b40?, 0x46ec90?, 0xc0?)
	/go/pkg/mod/github.com/shogo82148/androidbinary@v1.0.3/xml.go:215 +0x5e
github.com/shogo82148/androidbinary.(*XMLFile).readEndElement(0xc00013fe30, 0xc00046ec90)
	/go/pkg/mod/github.com/shogo82148/androidbinary@v1.0.3/xml.go:299 +0x10a
github.com/shogo82148/androidbinary.(*XMLFile).readChunk(0xc00013fe30, {0x8816c0?, 0xc0001b91a0}, 0x133e0)
	/go/pkg/mod/github.com/shogo82148/androidbinary@v1.0.3/xml.go:157 +0x167
github.com/shogo82148/androidbinary.NewXMLFile({0x8816c0?, 0xc0001b91a0})
	/go/pkg/mod/github.com/shogo82148/androidbinary@v1.0.3/xml.go:108 +0x14c
github.com/shogo82148/androidbinary/apk.(*Apk).parseManifest(0xc0001e4000)
	/go/pkg/mod/github.com/shogo82148/androidbinary@v1.0.3/apk/apk.go:162 +0x125
github.com/shogo82148/androidbinary/apk.OpenZipReader({0x882000?, 0xc000012a68?}, 0x0?)
	/go/pkg/mod/github.com/shogo82148/androidbinary@v1.0.3/apk/apk.go:61 +0x85
```

I am not familiar with the Android package. I just stumbled upon this panic, but there is no additional information on what happened.
If I find more information, I will keep you updated.

**Comment by shogo82148** [comment]
I can't access to ldfroezja.apk...

**Comment by Laitr0n** [comment]
> I can't access to ldfroezja.apk...

[ldfroezja.apk](https://1drv.ms/u/s!AtRFmgILoLowghJu098XjE6S5jSO?e=gYRSih)
I upload it to onedrive again.
